In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
import pickle
import numpy as np
import os

In [2]:
#from google.colab import files
#uploaded = files.upload()

In [3]:
file = open("data for next word prediction.txt", "r", encoding = "utf8")

# store file in list
lines = []
for i in file:
    lines.append(i)

print("$$$$$$$$$$$$$$$$$$$$$$$$$$$")
print(lines)
# Convert list to string
data = ""
for i in lines:
  data = ' '. join(lines) 

#replace unnecessary stuff with space
data = data.replace('\n', '').replace('\r', '').replace('\ufeff', '').replace('“','').replace('”','')  #new line, carriage return, unicode character --> replace by space

#remove unnecessary spaces 
data = data.split()
data = ' '.join(data)
data[:500]
len(data)

$$$$$$$$$$$$$$$$$$$$$$$$$$$
['The Project Gutenberg eBook of Pride and Prejudice\n', '    \n', 'This ebook is for the use of anyone anywhere in the United States and\n', 'most other parts of the world at no cost and with almost no restrictions\n', 'whatsoever. You may copy it, give it away or re-use it under the terms\n', 'of the Project Gutenberg License included with this ebook or online\n', 'at www.gutenberg.org. If you are not located in the United States,\n', 'you will have to check the laws of the country where you are located\n', 'before using this eBook.\n', '\n', 'Title: Pride and Prejudice\n', '\n', 'Author: Jane Austen\n', '\n', 'Release date: June 1, 1998 [eBook #1342]\n', '                Most recently updated: October 29, 2024\n', '\n', 'Language: English\n', '\n', 'Credits: Chuck Greif and the Online Distributed Proofreading Team at http://www.pgdp.net (This file was produced from images available at The Internet Archive)\n', '\n', '\n', '*** START OF THE PROJECT GUTENBE

220668

In [6]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])

# saving the tokenizer for predict function
pickle.dump(tokenizer, open('token.pkl', 'wb'))

sequence_data = tokenizer.texts_to_sequences([data])[0]
sequence_data[:15]
len(sequence_data)
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)
sequences = []

for i in range(3, len(sequence_data)):
    words = sequence_data[i-3:i+1]
    sequences.append(words)
    
print("The Length of sequences are: ", len(sequences))
sequences = np.array(sequences)
sequences[:10]
X = []
y = []

for i in sequences:
    X.append(i[0:3])
    y.append(i[3])
    
X = np.array(X)
y = np.array(y)
print("Data: ", X[:10])
print("Response: ", y[:10])
y = to_categorical(y, num_classes=vocab_size)
y[:5]

2401
The Length of sequences are:  11453
Data:  [[  1 425 347]
 [425 347 244]
 [347 244   2]
 [244   2 102]
 [  2 102   3]
 [102   3 183]
 [  3 183  46]
 [183  46 244]
 [ 46 244  11]
 [244  11  22]]
Response:  [244   2 102   3 183  46 244  11  22   1]


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=3))
model.add(LSTM(1000, return_sequences=True))
model.add(LSTM(1000))
model.add(Dense(1000, activation="relu"))
model.add(Dense(vocab_size, activation="softmax"))
model.summary()

e:\vs code software\python\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
from tensorflow import keras
from keras.utils import plot_model
#from keras.utils.vis_utils import plot_model

keras.utils.plot_model(model, to_file='plot.png', show_layer_names=True)

ValueError: This model has not yet been built. Build the model first by calling `build()` or by calling the model on a batch of data.

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint

checkpoint = ModelCheckpoint("next_words.h5", monitor='loss', verbose=1, save_best_only=True)
model.compile(loss="categorical_crossentropy", optimizer=Adam(learning_rate=0.001))
model.fit(X, y, epochs=70, batch_size=64, callbacks=[checkpoint])

Epoch 1/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 461ms/step - loss: 6.8518
Epoch 1: loss improved from inf to 6.62898, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 96s 464ms/step - loss: 6.8506
Epoch 2/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 428ms/step - loss: 6.2599
Epoch 2: loss improved from 6.62898 to 6.23779, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 77s 431ms/step - loss: 6.2598
Epoch 3/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 450ms/step - loss: 6.0620
Epoch 3: loss improved from 6.23779 to 6.02772, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 81s 453ms/step - loss: 6.0618
Epoch 4/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 479ms/step - loss: 5.7075
Epoch 4: loss improved from 6.02772 to 5.72623, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 87s 482ms/step - loss: 5.7076
Epoch 5/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 548ms/step - loss: 5.4560
Epoch 5: loss improved from 5.72623 to 5.46922, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 99s 554ms/step - loss: 5.4561
Epoch 6/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 503ms/step - loss: 5.2252
Epoch 6: loss improved from 5.46922 to 5.22347, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 134s 508ms/step - loss: 5.2252
Epoch 7/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 511ms/step - loss: 4.9743
Epoch 7: loss improved from 5.22347 to 5.00198, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 143s 514ms/step - loss: 4.9744
Epoch 8/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 534ms/step - loss: 4.7032
Epoch 8: loss improved from 5.00198 to 4.77552, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 96s 538ms/step - loss: 4.7036
Epoch 9/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 587ms/step - loss: 4.5256
Epoch 9: loss improved from 4.77552 to 4.56369, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 106s 591ms/step - loss: 4.5258
Epoch 10/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 643ms/step - loss: 4.2942
Epoch 10: loss improved from 4.56369 to 4.34028, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 116s 646ms/step - loss: 4.2944
Epoch 11/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 514ms/step - loss: 4.0378
Epoch 11: loss improved from 4.34028 to 4.10147, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 93s 518ms/step - loss: 4.0381
Epoch 12/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 582ms/step - loss: 3.7767
Epoch 12: loss improved from 4.10147 to 3.85697, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 154s 585ms/step - loss: 3.7771
Epoch 13/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 528ms/step - loss: 3.5173
Epoch 13: loss improved from 3.85697 to 3.59344, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 95s 531ms/step - loss: 3.5177
Epoch 14/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 508ms/step - loss: 3.2472
Epoch 14: loss improved from 3.59344 to 3.32907, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 92s 512ms/step - loss: 3.2476
Epoch 15/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 509ms/step - loss: 2.9530
Epoch 15: loss improved from 3.32907 to 3.04689, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 92s 512ms/step - loss: 2.9535
Epoch 16/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 504ms/step - loss: 2.6294
Epoch 16: loss improved from 3.04689 to 2.76551, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 91s 508ms/step - loss: 2.6302
Epoch 17/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 517ms/step - loss: 2.3957
Epoch 17: loss improved from 2.76551 to 2.48931, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 93s 520ms/step - loss: 2.3962
Epoch 18/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 512ms/step - loss: 2.1333
Epoch 18: loss improved from 2.48931 to 2.23757, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 92s 515ms/step - loss: 2.1339
Epoch 19/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 508ms/step - loss: 1.8440
Epoch 19: loss improved from 2.23757 to 2.00081, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 91s 511ms/step - loss: 1.8449
Epoch 20/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 508ms/step - loss: 1.6577
Epoch 20: loss improved from 2.00081 to 1.79255, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 142s 511ms/step - loss: 1.6585
Epoch 21/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 526ms/step - loss: 1.4453
Epoch 21: loss improved from 1.79255 to 1.55658, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 95s 529ms/step - loss: 1.4459
Epoch 22/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 513ms/step - loss: 1.2992
Epoch 22: loss improved from 1.55658 to 1.39060, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 93s 516ms/step - loss: 1.2997
Epoch 23/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 512ms/step - loss: 1.1403
Epoch 23: loss improved from 1.39060 to 1.22323, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 92s 515ms/step - loss: 1.1407
Epoch 24/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 511ms/step - loss: 1.0207
Epoch 24: loss improved from 1.22323 to 1.09472, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 142s 514ms/step - loss: 1.0212
Epoch 25/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 509ms/step - loss: 0.8387
Epoch 25: loss improved from 1.09472 to 0.91632, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 92s 512ms/step - loss: 0.8391
Epoch 26/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 516ms/step - loss: 0.7373
Epoch 26: loss improved from 0.91632 to 0.81094, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 93s 519ms/step - loss: 0.7377
Epoch 27/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 546ms/step - loss: 0.6500
Epoch 27: loss improved from 0.81094 to 0.72193, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 98s 549ms/step - loss: 0.6504
Epoch 28/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 530ms/step - loss: 0.5751
Epoch 28: loss improved from 0.72193 to 0.62179, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 96s 534ms/step - loss: 0.5753
Epoch 29/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 594ms/step - loss: 0.5119
Epoch 29: loss improved from 0.62179 to 0.56316, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 107s 597ms/step - loss: 0.5122
Epoch 30/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 539ms/step - loss: 0.4585
Epoch 30: loss improved from 0.56316 to 0.49095, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 97s 542ms/step - loss: 0.4586
Epoch 31/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 536ms/step - loss: 0.3827
Epoch 31: loss improved from 0.49095 to 0.43184, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 97s 539ms/step - loss: 0.3830
Epoch 32/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 563ms/step - loss: 0.3443
Epoch 32: loss improved from 0.43184 to 0.39274, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 101s 567ms/step - loss: 0.3446
Epoch 33/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 515ms/step - loss: 0.3343
Epoch 33: loss improved from 0.39274 to 0.38134, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 93s 519ms/step - loss: 0.3345
Epoch 34/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 525ms/step - loss: 0.2987
Epoch 34: loss improved from 0.38134 to 0.33967, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 95s 528ms/step - loss: 0.2989
Epoch 35/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 525ms/step - loss: 0.3047
Epoch 35: loss did not improve from 0.33967
179/179 ━━━━━━━━━━━━━━━━━━━━ 94s 525ms/step - loss: 0.3049
Epoch 36/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 533ms/step - loss: 0.2552
Epoch 36: loss improved from 0.33967 to 0.32712, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 144s 536ms/step - loss: 0.2556
Epoch 37/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 527ms/step - loss: 0.2799
Epoch 37: loss improved from 0.32712 to 0.30917, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 95s 530ms/step - loss: 0.2800
Epoch 38/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 514ms/step - loss: 0.2610
Epoch 38: loss improved from 0.30917 to 0.28118, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 93s 518ms/step - loss: 0.2611
Epoch 39/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 506ms/step - loss: 0.2403
Epoch 39: loss improved from 0.28118 to 0.25770, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 141s 510ms/step - loss: 0.2404
Epoch 40/70
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 506ms/step - loss: 0.2021
Epoch 40: loss improved from 0.25770 to 0.23950, saving model to next_words.h5


179/179 ━━━━━━━━━━━━━━━━━━━━ 91s 509ms/step - loss: 0.2024
Epoch 41/70
 24/179 ━━━━━━━━━━━━━━━━━━━━ 1:29 577ms/step - loss: 0.1578

In [ ]:
from tensorflow.keras.models import load_model
import numpy as np
import pickle

# Load the model and tokenizer
model = load_model('next_words.h5')
tokenizer = pickle.load(open('token.pkl', 'rb'))

def Predict_Next_Words(model, tokenizer, text):

  sequence = tokenizer.texts_to_sequences([text])
  sequence = np.array(sequence)
  preds = np.argmax(model.predict(sequence))
  predicted_word = ""
  
  for key, value in tokenizer.word_index.items():
      if value == preds:
          predicted_word = key
          break
  
  print(predicted_word)
  return predicted_word

In [ ]:
while(True):
  text = input("Enter your line: ")
  
  if text == "0":
      print("Execution completed.....")
      break
  
  else:
      try:
          text = text.split(" ")
          text = text[-3:]
          print(text)
        
          Predict_Next_Words(model, tokenizer, text)
          
      except Exception as e:
        print("Error occurred: ",e)
        continue